### ISSUE TITLE
Re-investigate Beam and Transforms regarding IsSideInput

### ISSUE THREAD

**Issue by wonook** [snuspl/nemo#508]
We have transformed BEAM DAGs to our IR DAG, and as a result we ended up with having SideInputs, which are needed when broadcasting data. We should think of another way to express this part, to be able to move away from BEAM.

**Comment by johnyangk** [comment]
At a high-level, sideInputs(and broadcasted data) are globally accessible, named data.  In both Beam and Spark, such data are dynamically accessed by user-defined functions for processing each data element.

Considering this, another method would be to introduce a new component(edge or vertex or annotation) in the Onyx IR to represent such data. I don't have concrete ideas at this point though. I'd first try to understand the differences between Beam and Spark and see if a common interface is possible.

**Comment by wonook** [comment]
Refer #754

**Comment by wonook** [comment]
https://issues.apache.org/jira/projects/NEMO/issues/NEMO-14?filter=allopenissues
