### ISSUE TITLE
Replace MetricCollectionBarrierVertex with a Customizable IRVertex

### ISSUE THREAD

**Issue by jooykim** [snuspl/nemo#513]
Rather than adding a type of an `IRVertex` when a need arises,
it would be better to create a customizable `IRVertex`, which is added to the DAG with a reshaping pass.

We can implement `MetricCollectionBarrierVertex` with this customizable `IRVertex`.

**Comment by sanha** [comment]
Moved to JIRA [NEMO-19](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-19?filter=allopenissues)
