### ISSUE TITLE
Introduce KeyAssignment

### ISSUE THREAD

**Issue by jooykim** [snuspl/nemo#659]
We currently have "hash" assignments for data blocks integrated into `PartitionManager`.

We should rename this term to "key".
The code to assign the partition keys of a block to each consumer task should be provided as a separate interface, `KeyAssignment`.

Related to #492

**Comment by sanha** [comment]
Moved to JIRA [NEMO-22](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-22?filter=allopenissues)
