### ISSUE TITLE
Bump up the Beam version to 2.3.0

### ISSUE THREAD

**Issue by johnyangk** [snuspl/nemo#676]
Bump up the version from 2.0.0 to 2.3.0.
- full Java 8 support
- Spark 2.x support in Spark runner
- Amazon WS S3 filesystem support
- General-purpose writing to files (FileIO)
- Splittable DoFn support in Python SDK
- Improvements on Portability layer
- Improvements on SDKs & runners
- Improvements on several IOs

**Comment by johnyangk** [comment]
Apparently Beam 2.3.0 will support Spark 2.X, as [this PR](https://github.com/apache/beam/pull/4208) was merged in the Beam master branch on Dec 18th.

The latest version of Beam (2.2.0) supporting Spark 1.6 was released on Dec 14th.

**Comment by wonook** [comment]
Beam 2.3.0 has been released with the following updates, can you update the issue description?

- full Java 8 support
- Spark 2.x support in Spark runner
- Amazon WS S3 filesystem support
- General-purpose writing to files (FileIO)
- Splittable DoFn support in Python SDK
- Improvements on Portability layer
- Improvements on SDKs & runners
- Improvements on several IOs

File IO has been the main thing blocking this issue, and apparently there had been an update regarding this bit, so upgrading Beam version straight to 2.3.0 makes more sense to me.

**Comment by johnyangk** [comment]
Done. :)

**Comment by johnyangk** [comment]
Moved to https://issues.apache.org/jira/projects/NEMO/issues/NEMO-3.
