### ISSUE TITLE
Sleep Time Per Container Type in SchedulingPolicy

### ISSUE THREAD

**Issue by jooykim** [snuspl/nemo#696]
`SchedulingPolicy` sleeps for a given amount of time when a container, given a TaskGroup is unavailable for scheduling.

However, other container types for other TaskGroups may be available for scheduling immediately.
We sacrifice on the job completion time depending on this time (especially because the default is now 10s).

**Comment by sanha** [comment]
Moved to JIRA [NEMO-23](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-23?filter=allopenissues)
