### ISSUE TITLE
Refactor TaskGroupExecutor to a batch/stream-unified execution model

### ISSUE THREAD

**Issue by jeongyooneo** [snuspl/nemo#717]
Currently, the execution model of `TaskGroupExecutor` is strictly batch-manner; each `Task` is executed only once, getting possibly OOM-incurrable size `Iterable` as input.

This execution model needs to be changed as following:
- `Task`s that gets inter-`TaskGroup` input process mini-batch size data
- `Task`s that gets intra-`TaskGroup` input process data in a pipelined manner: as `Task`'s output becomes available, the next `Task` processes it right away

This is a sub-issue of #432.

**Comment by johnyangk** [comment]
@sanha Can you leave a comment on how this also addresses `null`s in `DataTransferFactory`?

**Comment by sanha** [comment]
If intra-TaskGroup input data can be processed in a pipelined manner, Intra-TaskGroup edges do not need `InputReader` & `OutputWriter` anymore. Therefore, the `null` and `@Nullable` in `DataTrnasferFactory`, `InputReader`, and `OutputWriter` can be removed.

**Comment by jeongyooneo** [comment]
Moved to https://issues.apache.org/jira/browse/NEMO-7.
