### ISSUE TITLE
Set HashRange to a prime number

### ISSUE THREAD

**Issue by jeongyooneo** [snuspl/nemo#773]
Currently, skew handling uses `dstParallelism * HashRangeMultiplier` as a hash range. This is a non-prime number, thus sometimes distribute partitions like the following:

<img src="https://user-images.githubusercontent.com/6097406/35951540-19998760-0cbf-11e8-90f5-e90ca76948be.png" width="500" height="250">

To mitigate this, we need to set hash range as a prime number.

**Comment by sanha** [comment]
Close via #774
