### ISSUE TITLE
Executor side metric logs aren't sent to Master

### ISSUE THREAD

**Issue by jeongyooneo** [snuspl/nemo#782]
Executor side metric logs, which are sent to Master via ControlMessage, aren't sent to Master in local environment. However in AWS clusters the logs are sent well.
We need to find the root cause of this problem and fix it.

**Comment by sanha** [comment]
Oddly, the metric logs are sent to driver in my local environment.

**Comment by jeongyooneo** [comment]
This occurs occasionally in local environment, but is presumed to occur under local settings with problems.
